### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by zinete** [tesseract-one/react-native-gomobile-ipfs#1]
Hello brother. I got this error when installing this package. How can I fix it?

![image](https://user-images.githubusercontent.com/23396979/121834772-29368680-cd02-11eb-96fe-f86aa730aec1.png)

**Comment by ypopovych** [comment]
Seems as something happened to https://github.com/ipfs-shipyard/gomobile-ipfs library. Can you check with them, please?
